export default {
  language: 'Language', persian: 'فارسی', english: 'English',
  auth: { title: 'Sign in to dashboard', description: 'Sign in to access your market research reports.', email: 'Email', password: 'Password', submit: 'Sign in', invalid: 'Incorrect email or password.' },
  common: { cancel: 'Cancel', close: 'Close', save: 'Save', delete: 'Delete', confirm: 'Confirm', back: 'Back', loading: 'Loading…', error: 'Error', optional: 'Optional', required: 'Required', yes: 'Yes', no: 'No' },
  loading: { title: 'Building your report...', wait: 'Please wait. This process may take a few minutes.', error: 'Processing error', fetch: 'Fetching Instagram data from Apify…', analyze: 'Analyzing competitor data…', ai: 'Analyzing research data…', generate: 'Generating final report…' },
  form: { title: 'Market Research Builder', subtitle: 'A complete market and digital-channel analysis dashboard', archive: 'Saved projects', target: 'Target business', competitors: 'Competitors', addCompetitor: 'Add competitor', businessName: 'Business name', industry: 'Industry / business area', location: 'Research geography', audienceLanguage: 'Audience language', marketScope: 'Market scope', instagram: 'Instagram handle', website: 'Website address', discover: 'Discover industry', submit: 'Start market research', settings: 'Analysis model settings' },
  industry: { title: 'See the industry map before choosing competitors', description: 'Discover market segments and players using the selected industry, geography, and market scope.', discovering: 'Discovering…', update: 'Update map', scope: 'Scope', market: 'Market', audience: 'Audience language' },
  cpm: { title: 'Expert model approval', approve: 'Approve, lock and continue', equalize: 'Equalize', factorWeight: 'Factor weight', definition: 'Definition', reason: 'Selection rationale', confidence: 'Confidence', high: 'High', medium: 'Medium', low: 'Low' },
  dashboard: { report: 'Market research report', projects: 'Projects', currentPage: 'Current page', fullReport: 'Full report', presentation: 'Build presentation', target: 'Target brand', competitor: 'Competitor', insufficientData: 'Insufficient data', tabs: { industry: 'Industry & market', directory: 'Competitors at a glance', competitors: 'Competitor profiles', comparison: 'Comparative analysis', swot: 'SWOT', topics: 'Evergreen topics', cpm: 'Detailed CPM', maps: 'Positioning maps', strategy: 'Recommendations', sources: 'Sources' } },
};
