import { useMemo, useState } from 'react';
import { ArrowRight, ExternalLink, Printer } from 'lucide-react';
import { CartesianGrid, ReferenceLine, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis } from 'recharts';
import { buildCpmPositioningMaps } from '../utils/cpm.js';
import './cpm.css';

const TABS = [
  ['industry','صنعت و بازار'],['directory','رقبا در یک نگاه'],['competitors','پرونده رقبا'],
  ['comparison','تحلیل تطبیقی'],['swot','SWOT'],['cpm','CPM مفصل'],['maps','نقشه جایگاه'],['strategy','پیشنهادات'],['sources','منابع'],
];
const FACTORS = {
  instagramBreakdown: ['Instagram','visualQuality','creativity','scriptTopic','captions','storytelling','bio','highlights','layout','engagementRate'],
  websiteBreakdown: ['Website','ux','deviceCompatibility','seo','serviceCategorization','onlineBooking','liveSupport'],
  credibilityBreakdown: ['اعتماد و اعتبار','physicalStore','digitalPresence','influencerCollabs','yearsExperience'],
  servicesBreakdown: ['محصول و خدمات','productDiversity','customization','accessories','additionalServices'],
};
const LABELS = {visualQuality:'کیفیت بصری',creativity:'خلاقیت',scriptTopic:'سناریو و موضوع',captions:'کپشن',storytelling:'داستان‌گویی',bio:'بیو',highlights:'هایلایت',layout:'چیدمان',engagementRate:'نرخ تعامل',ux:'تجربه کاربری',deviceCompatibility:'سازگاری موبایل',seo:'سئو',serviceCategorization:'دسته‌بندی خدمات',onlineBooking:'رزرو آنلاین',liveSupport:'پشتیبانی زنده',physicalStore:'مکان فیزیکی',digitalPresence:'حضور دیجیتال',influencerCollabs:'همکاری تبلیغاتی',yearsExperience:'سابقه',productDiversity:'تنوع محصول',customization:'شخصی‌سازی',accessories:'محصول مکمل',additionalServices:'خدمات تکمیلی'};
const n = (value) => value == null ? '—' : Number(value) >= 1000 ? `${(Number(value)/1000).toFixed(1)}K` : value;
const arr = (value) => Array.isArray(value) ? value : [];
const date = (value) => { if(!value) return '—'; const parsed=new Date(value); return Number.isNaN(parsed.getTime())?value:new Intl.DateTimeFormat('fa-IR',{year:'numeric',month:'long',day:'numeric'}).format(parsed); };
const state = (value, yes, no) => value == null ? 'نامشخص' : value ? yes : no;

function Panel({title,kicker,children,className=''}) { return <section className={`rd-panel ${className}`}><header><span>{kicker}</span><h2>{title}</h2></header>{children}</section>; }
function Empty({children='داده‌ای برای این بخش دریافت نشده است.'}) { return <p className="rd-empty">{children}</p>; }
function Link({href,children}) { if(!href) return null; const url=href.startsWith('http')?href:`https://${href}`; return <a href={url} target="_blank" rel="noreferrer">{children}<ExternalLink size={12}/></a>; }
function ScoreBar({label,value}) { const score=Math.max(0,Math.min(10,Number(value)||0)); return <div className="rd-score"><span>{label}</span><i><b style={{width:`${score*10}%`}}/></i><strong>{score}</strong></div>; }
function UnitScore({label,value}) { const score=value==null?null:Math.max(0,Math.min(1,Number(value)||0)); return <div className="rd-score rd-score-unit"><span>{label}</span><i><b style={{width:`${(score||0)*100}%`}}/></i><strong>{score==null?'—':score.toFixed(2)}</strong></div>; }
function PercentBar({label,value}) { const percent=Math.max(0,Math.min(100,Number(value)||0)); return <div className="rd-score"><span>{LABELS[label]||({photos:'عکس',videos:'ویدئو',carousels:'کاروسل'}[label])||label}</span><i><b style={{width:`${percent}%`}}/></i><strong>{percent}%</strong></div>; }

function Industry({data,target}) { return <div className="rd-grid"><Panel className="rd-span-2" kicker="MARKET DEFINITION" title={`نمای کلی ${target?.industry||'صنعت'}`}><p className="rd-lead">{data.industryOverview||'تحلیل صنعت در دسترس نیست.'}</p></Panel><Panel kicker="MARKET SEGMENTS" title="بخش‌های اصلی بازار"><div className="rd-segments">{arr(data.marketCategories).map((x,i)=><div key={x.name}><span>{i+1}. {x.name}</span><strong>{x.share??'—'}%</strong></div>)}</div></Panel><Panel kicker="RESEARCH SCOPE" title="دامنه مطالعه"><dl className="rd-dl"><div><dt>برند هدف</dt><dd>{target?.name||'—'}</dd></div><div><dt>تعداد رقبا</dt><dd>{arr(data.competitorAnalysis).length}</dd></div><div><dt>کانال‌های اصلی</dt><dd>Instagram · Website</dd></div><div><dt>روش</dt><dd>داده عمومی + تحلیل تطبیقی</dd></div></dl></Panel></div>; }

function Directory({data}) { const list=data.competitorAnalysis?.length?data.competitorAnalysis:data.competitorList; return <Panel kicker="COMPETITIVE LANDSCAPE" title="رقبا در یک نگاه"><div className="rd-table"><table><thead><tr><th>برند</th><th>موقعیت</th><th>Instagram</th><th>Website</th><th>مخاطب</th><th>امتیاز</th></tr></thead><tbody>{arr(list).map((c,i)=><tr key={`${c.name||'competitor'}-${i}`}><td><b>{c.name}</b></td><td>{c.location||'—'}</td><td><Link href={`https://instagram.com/${String(c.instagramHandle||'').replace('@','')}`}>{c.instagramHandle||'—'}</Link></td><td><Link href={c.website}>{c.website||'—'}</Link></td><td>{n(c.followers??c.instagramAnalytics?.followers)}</td><td>{c.overallScore??'—'}/10</td></tr>)}</tbody></table></div></Panel>; }

function Competitor({comp,index}) { const ig=comp.instagramAnalytics||{}; const web=comp.websiteAnalytics||{}; const verifiedFirst=ig.firstPostStatus==='verified'?ig.firstPost:null; return <article className="rd-competitor"><div className="rd-competitor-head"><span>{String(index+1).padStart(2,'0')}</span><div><small>COMPETITOR PROFILE</small><h2>{comp.name}</h2><p>{comp.bio||comp.description||comp.location||'اطلاعات معرفی در دسترس نیست.'}</p></div><strong>{comp.overallScore??'—'}<small>/10</small></strong></div><div className="rd-grid"><Panel kicker="BUSINESS MODEL" title="مدل کسب‌وکار و خدمات"><div className="rd-tags">{arr(comp.services).map(x=><span key={x}>{x}</span>)}</div><h3>اقدامات بازاریابی و برندینگ</h3><ul>{arr(comp.marketingActions).map(x=><li key={x}>{x}</li>)}</ul></Panel><Panel kicker="INSTAGRAM SNAPSHOT · APIFY" title="شاخص‌های قطعی نمونه"><dl className="rd-dl"><div><dt>اولین پست کل پیج</dt><dd>{verifiedFirst?date(verifiedFirst):'جمع‌آوری نشده'}</dd></div><div><dt>قدیمی‌ترین پست نمونه</dt><dd>{date(ig.oldestSampledPost)}</dd></div><div><dt>جدیدترین پست نمونه</dt><dd>{date(ig.lastPost)}</dd></div><div><dt>پست بررسی‌شده</dt><dd>{ig.postsAnalyzed??'—'}</dd></div><div><dt>کل پست‌های پیج</dt><dd>{ig.totalPosts??comp.posts??'—'}</dd></div><div><dt>فالوور</dt><dd>{n(ig.followers??comp.followers)}</dd></div><div><dt>نرخ تعامل نمونه</dt><dd>{ig.engagementRate==null?'نامشخص':`${ig.engagementRate}%`}</dd></div></dl><p className="rd-empty">تاریخ قدیمی‌ترین پست نمونه، تاریخ ایجاد یا اولین پست پیج نیست.</p></Panel><Panel className="rd-span-2" kicker="CONTENT AUDIT · SAMPLE" title="تحلیل محتوای Instagram"><div className="rd-analysis">{Object.entries(ig.contentAnalysis||{}).map(([key,value])=><div key={key}><b>{LABELS[key]||key}</b><p>{value}</p></div>)}</div>{!Object.keys(ig.contentAnalysis||{}).length&&<Empty/>}<div className="rd-format">{Object.entries(ig.mediaDistribution||{}).map(([key,value])=><PercentBar key={key} label={key} value={value}/>)}</div>{ig.bestContent?.link&&<div className="rd-best"><span>محتوای برتر در نمونه بررسی‌شده</span><b>{ig.bestContent.title}</b><Link href={ig.bestContent.link}>مشاهده پست</Link></div>}</Panel><Panel className="rd-span-2" kicker="WEBSITE AUDIT" title="تحلیل Website"><div className="rd-web"><div><span>UX</span><strong>{web.uxScore==null?'نامشخص':`${web.uxScore}/10`}</strong></div><div><span>Mobile</span><strong>{state(web.mobileFriendly,'مناسب','نیازمند بهبود')}</strong></div><div><span>SEO</span><strong>{web.seoStatus||'نامشخص'}</strong></div><div><span>رزرو آنلاین</span><strong>{state(web.onlineBooking,'فعال','غیرفعال')}</strong></div><div><span>پشتیبانی</span><strong>{state(web.liveSupport,'فعال','غیرفعال')}</strong></div></div>{web.narrative&&<p className="rd-narrative" style={{marginTop:'16px',fontSize:'0.9rem',lineHeight:'1.6',color:'#b2c3c7'}}>{web.narrative}</p>}</Panel></div></article>; }

function Comparison({data}) { return <div className="rd-grid"><Panel kicker="BENCHMARK" title="مقایسه نقاط قوت"><div className="rd-compare">{arr(data.competitorAnalysis).map(c=><div key={c.name}><h3>{c.name}</h3>{arr(c.strengths).map(x=><p key={x}>+ {x}</p>)}</div>)}</div></Panel><Panel kicker="MARKET GAPS" title="شکاف‌ها و نقاط ضعف"><div className="rd-compare">{arr(data.competitorAnalysis).map(c=><div key={c.name}><h3>{c.name}</h3>{arr(c.weaknesses).map(x=><p key={x}>− {x}</p>)}</div>)}</div></Panel></div>; }
function Swot({data}) { return <div className="rd-swot">{[['strengths','نقاط قوت'],['weaknesses','نقاط ضعف'],['opportunities','فرصت‌ها'],['threats','تهدیدها']].map(([key,title],i)=><Panel key={key} kicker={['S','W','O','T'][i]} title={title}>{arr(data.swot?.[key]).map(x=><p key={x}>{x}</p>)}</Panel>)}</div>; }
function LegacyCpm({data}) { return <><Panel kicker="WEIGHTED RESULT" title="جدول امتیازات نهایی"><div className="rd-table"><table><thead><tr><th>برند</th><th>Instagram</th><th>Website</th><th>اعتبار</th><th>محصول</th><th>مجموع</th></tr></thead><tbody>{arr(data.cpmMatrix?.rows).map(r=><tr key={r.name} className={r.isTarget?'is-target':''}><td><b>{r.name}</b></td><td>{r.instagram}</td><td>{r.website}</td><td>{r.credibility}</td><td>{r.services}</td><td><b>{r.total}</b></td></tr>)}</tbody></table></div></Panel><div className="rd-cpm-cards">{arr(data.cpmMatrix?.rows).map(row=><Panel key={row.name} kicker={row.isTarget?'TARGET BRAND':'COMPETITOR'} title={row.name}>{Object.entries(FACTORS).map(([group,items])=><div className="rd-factor" key={group}><h3>{items[0]}</h3>{items.slice(1).map(key=><ScoreBar key={key} label={LABELS[key]} value={row[group]?.[key]}/>)}</div>)}</Panel>)}</div></>; }
function DynamicCpm({data}) {
  const model=data.cpmModel; const rows=arr(data.cpmMatrix?.rows);
  return <>
    <Panel kicker="APPROVED METHODOLOGY" title="مدل کارشناسی تأییدشده">
      <p className="rd-cpm-note">{model.rationale}</p>
      <div className="rd-cpm-model-grid">{model.factors.map(factor=><article key={factor.id}><div><b>{factor.label}</b><strong>{Math.round(Number(factor.weight)*100)}٪</strong></div><p>{factor.weightRationale||factor.reason}</p><small>اطمینان: {factor.confidence==='high'?'بالا':factor.confidence==='low'?'پایین':'متوسط'}</small></article>)}</div>
      <p className="rd-cpm-lock">نسخه {model.version} · قفل‌شده برای تمام رقبا · {model.operatorEdited?'اصلاح‌شده و تأییدشده توسط اپراتور':'تأییدشده توسط اپراتور'}</p>
    </Panel>
    <Panel kicker="PROJECT-SPECIFIC CPM · LOCKED" title="جدول امتیازات نرمال‌شده و وزنی"><p className="rd-cpm-note">محاسبات با دقت کامل انجام شده‌اند؛ نمایش امتیازها در بازه صفر تا یک است.</p><div className="rd-table"><table><thead><tr><th>برند</th>{model.factors.map(f=><th key={f.id}>{f.label}<small className="rd-cpm-weight">وزن {Math.round(Number(f.weight)*100)}٪</small></th>)}<th>CPM وزنی</th></tr></thead><tbody>{rows.map(row=><tr key={row.name} className={row.isTarget?'is-target':''}><td><b>{row.name}</b></td>{model.factors.map(f=><td key={f.id}>{row.factorScores?.[f.id]?.score==null?'—':row.factorScores[f.id].score.toFixed(2)}</td>)}<td><b>{row.total==null?'—':row.total.toFixed(2)}</b></td></tr>)}</tbody></table></div></Panel>
    <div className="rd-cpm-cards">{rows.map(row=><Panel key={row.name} kicker={row.isTarget?'TARGET BRAND':'COMPETITOR'} title={row.name}>{model.factors.map(factor=><div className="rd-factor" key={factor.id}><h3>{factor.label} <small>وزن {Math.round(Number(factor.weight)*100)}٪ · {row.factorScores?.[factor.id]?.score==null?'—':row.factorScores[factor.id].score.toFixed(2)}</small></h3>{factor.dependentVariables.map(dependent=>{const dependentResult=row.factorScores?.[factor.id]?.dependentScores?.[dependent.id];return <div className="rd-cpm-dependent" key={dependent.id}><div><b>{dependent.label} <small>({Math.round(Number(dependent.weight)*100)}٪)</small></b><strong>{dependentResult?.score==null?'—':dependentResult.score.toFixed(2)}</strong></div>{dependent.independentVariables.map(criterion=>{const result=dependentResult?.independentScores?.[criterion.id];return <div className="rd-cpm-criterion" key={criterion.id}><UnitScore label={`${criterion.label} · ${Math.round(Number(criterion.weight)*100)}٪`} value={result?.normalizedScore}/><small>{result?.rawScore==null?'داده ناکافی':`${result.rawScore} از ${criterion.scoring.max}`}</small>{result?.evidence&&<p>{result.evidence}</p>}</div>})}</div>})}</div>)}</Panel>)}</div>
  </>;
}
function FactorOverviews({data}) { const labels={social:'سوشال',website:'وب‌سایت',product_service:'محصول / خدمت',industry_specific:'عوامل ویژه صنعت'}; const items=Object.entries(data.factorOverviews||{}); if(!items.length)return null; return <Panel kicker="QUALITATIVE READOUT" title="مقدمه کیفی فاکتورهای رقابتی"><p className="rd-cpm-note">این جمع‌بندی بعد از تحلیل امتیازها و شواهد هر فاکتور ساخته شده است؛ اعداد در جدول پایین قابل مشاهده‌اند.</p><div className="rd-factor-overviews">{items.map(([key,value])=><article key={key}><span>{labels[key]||key}</span><p>{value}</p></article>)}</div></Panel>; }
function Cpm({data}) { return data.cpmModel?<><FactorOverviews data={data}/><DynamicCpm data={data}/></>:<LegacyCpm data={data}/>; }
function Maps({data}) {
  const targetName=arr(data.cpmMatrix?.rows).find((row)=>row.isTarget)?.name;
  const maps=data.cpmModel?buildCpmPositioningMaps(data.cpmModel,data.cpmMatrix):arr(data.positioningMaps);
  return <div className="rd-maps">{maps.map((map,i)=>{
    const points=arr(map.data).map((point)=>({...point,isTarget:Boolean(point.isTarget||point.name===targetName)})); const targetPoints=points.filter((point)=>point.isTarget); const competitorPoints=points.filter((point)=>!point.isTarget);
    const domain=map.domain||[0,10]; const midpoint=map.midpoint??5; const isCpmMap=map.source==='cpm_factor_scores';
    return <Panel key={map.title||i} kicker={isCpmMap?'CPM POSITIONING MAP':'POSITIONING MAP'} title={map.title||`نقشه ${i+1}`}><div className="rd-map-legend"><span><i className="target"/>برند هدف</span><span><i className="competitor"/>رقبا</span></div><ResponsiveContainer width="100%" height={310}><ScatterChart margin={{top:14,right:20,bottom:20,left:0}}><CartesianGrid stroke="#2b3c43" strokeDasharray="3 3"/><XAxis type="number" dataKey="x" name={map.xAxis} domain={domain} tick={{fill:'#84969b'}} tickFormatter={(value)=>Number(value).toFixed(isCpmMap?1:0)}/><YAxis type="number" dataKey="y" name={map.yAxis} domain={domain} tick={{fill:'#84969b'}} tickFormatter={(value)=>Number(value).toFixed(isCpmMap?1:0)}/><ReferenceLine x={midpoint} stroke="#53656b"/><ReferenceLine y={midpoint} stroke="#53656b"/><Tooltip cursor={{stroke:'#70838a',strokeDasharray:'3 3'}} content={({active,payload})=>active&&payload?.[0]?<div className="rd-map-tooltip"><b>{payload[0].payload.name}</b><span>{payload[0].payload.isTarget?'برند هدف':'رقیب'}</span><small>{map.xAxis}: {Number(payload[0].payload.x).toFixed(isCpmMap?2:0)} · {map.yAxis}: {Number(payload[0].payload.y).toFixed(isCpmMap?2:0)}</small></div>:null}/><Scatter name="رقبا" data={competitorPoints} fill="#58c6bd" shape="circle"/><Scatter name="برند هدف" data={targetPoints} fill="#f2b35f" shape="diamond"/></ScatterChart></ResponsiveContainer><p>{map.xAxis} × {map.yAxis}{isCpmMap?' · استخراج مستقیم از CPM تأییدشده':''}</p>{!points.length&&<Empty>برای این دو فاکتور امتیاز مشترک کافی وجود ندارد.</Empty>}</Panel>})}</div>;
}
function Strategy({data}) { return <div className="rd-recs">{arr(data.recommendations).map((x,i)=><Panel key={x.title} kicker={`PRIORITY ${x.priority||i+1}`} title={x.title}><p>{x.description}</p>{x.actionSteps&&<ul>{arr(x.actionSteps).map(a=><li key={a}>{a}</li>)}</ul>}</Panel>)}</div>; }
function Sources({data}) { const links=new Set(); arr(data.competitorAnalysis).forEach(c=>{if(c.website)links.add(c.website);if(c.instagramHandle)links.add(`https://instagram.com/${String(c.instagramHandle).replace('@','')}`);if(c.instagramAnalytics?.bestContent?.link)links.add(c.instagramAnalytics.bestContent.link)}); return <Panel kicker="EVIDENCE REGISTER" title="منابع و شواهد"><ol className="rd-sources">{[...links].map(x=><li key={x}><Link href={x}>{x}</Link></li>)}</ol>{!links.size&&<Empty/>}</Panel>; }

export default function ResearchDashboard({data,target,isMock,onReset}) {
  const [tab,setTab]=useState('industry'); const [selected,setSelected]=useState(0); const [printingAll,setPrintingAll]=useState(false);
  const competitor=arr(data.competitorAnalysis)[selected];
  const sections=useMemo(()=>({industry:<Industry data={data} target={target}/>,directory:<Directory data={data}/>,competitors:<><div className="rd-subtabs">{arr(data.competitorAnalysis).map((c,i)=><button key={`${c.name||'competitor'}-${i}`} onClick={()=>setSelected(i)} className={selected===i?'active':''}>{c.name}</button>)}</div>{competitor?<Competitor comp={competitor} index={selected}/>:<Empty/>}</>,comparison:<Comparison data={data}/>,swot:<Swot data={data}/>,cpm:<Cpm data={data}/>,maps:<Maps data={data}/>,strategy:<Strategy data={data}/>,sources:<Sources data={data}/>}),[data,target,selected,competitor]);
  const print=(all)=>{setPrintingAll(all);setTimeout(()=>window.print(),80)};
  return <div className="rd" dir="rtl"><header className="rd-top"><button onClick={onReset}><ArrowRight size={16}/> پروژه‌ها</button><div><b>{target?.name||'گزارش تحقیق بازار'}</b><span>Market Research · v0.0.2 {isMock?'· DEMO':''}</span></div><div><button onClick={()=>print(false)}><Printer size={15}/> صفحه جاری</button><button onClick={()=>print(true)}><Printer size={15}/> کل گزارش</button></div></header><nav className="rd-tabs">{TABS.map(([id,label])=><button key={id} onClick={()=>{setPrintingAll(false);setTab(id)}} className={tab===id?'active':''}>{label}</button>)}</nav><main className="rd-main">{printingAll?TABS.map(([id,label])=><section className="rd-print-section" key={id}><h1>{label}</h1>{sections[id]}</section>):sections[tab]}</main></div>;
}
